### ISSUE TITLE
Error during creation of NTAG using non NTAG215

### ISSUE THREAD

**Issue by YozenPL** [AcK77/AmiiBomb-uino#1]
Hello,

Please create a restriction in application for other tags - different than NTAG215.
During creation of NTAG if you use "non NTAG215" tag, application will crash.

ERROR:
Name of parameter: length
   w System.String.Substring(Int32 startIndex, Int32 length)
   w AmiiBomb.Amiibo_Class.Calculate_Long_UID(String Short_UID)
   w AmiiBomb.Flash_Form.<button2_Click>d__9.MoveNext()

**Comment by AcK77** [comment]
Hi,
Nice idea here, in my test I just use NTAG215 but in fact if anyone doesn't know what's kind of tag is, it's great to check it! I'll try to fix that soon!

**Comment by AcK77** [comment]
Fixed in AmiiBomb v0.3 Alpha. Thanks.
