### ISSUE TITLE
Cathegories in Dumps directory

### ISSUE THREAD

**Issue by YozenPL** [AcK77/AmiiBomb-uino#12]
Could you add an option to categorise the amiibos in Dump folder? (just by creating new folder for specific series)
Like:
```
|-AmiBomb
   |- Dumps
       |- Splatoon
           |- file1.bin
           |- file2.bin
       |- Zelda
           |- filex.bin
```

**Comment by kokkie20** [comment]
If i am correct that is in version 0.3, at least for me it is 
You should make some folders and sort them. For me on the top of the list view are the folders and under that is the file list
@YozenPL

**Comment by AcK77** [comment]
Yes it's already exist in last version by create a directory in windows... No need to reinvent the wheel ^^!
