### ISSUE TITLE
Unhandled exception error 

### ISSUE THREAD

**Issue by Zombuino** [AcK77/AmiiBomb-uino#13]
Using UNO R3.  I can successfully flash the firmware for my Arduino using both 0.2 and 0.3 versions.  

When i try to dump it reads the Amiibo successfully but as soon as it finishes reading it I receive an Unhandled Exception Error.  This happened on two different Windows 10 machines. See screenshot:

![amiibomb error screenshot1](https://user-images.githubusercontent.com/30484862/28651235-9560304e-724e-11e7-94e0-35ac9346a4df.png)

Details of error:
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.NullReferenceException: Object reference not set to an instance of an object.
   at AmiiBomb.Amiibo_Class.Decrypt(Byte[] Data, AmiiboKeys Keyfile)
   at AmiiBomb.Flash_Form.<button2_Click>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)

************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2101.1 built by: NET47REL1LAST
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
AmiiBomb
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///F:/Amiibo%20Stuff/AmiiBomb_0.2_Alpha_by_Ac_K/AmiiBomb.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2094.0 built by: NET47REL1LAST
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2093.0 built by: NET47REL1LAST
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2046.0 built by: NET47REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2046.0 built by: NET47REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2099.0 built by: NET47REL1LAST
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2046.0 built by: NET47REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Newtonsoft.Json
    Assembly Version: 10.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///F:/Amiibo%20Stuff/AmiiBomb_0.2_Alpha_by_Ac_K/AmiiBomb.exe
----------------------------------------
System.Numerics
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2046.0 built by: NET47REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll
----------------------------------------
System.Runtime.Serialization
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2046.0 built by: NET47REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll
----------------------------------------
System.Data
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2046.0 built by: NET47REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_32/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------
System.Management
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2096.0 built by: NET47REL1LAST
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Management/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Management.dll
----------------------------------------
NLog
    Assembly Version: 4.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///F:/Amiibo%20Stuff/AmiiBomb_0.2_Alpha_by_Ac_K/AmiiBomb.exe
----------------------------------------
System.ServiceModel
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2046.0 built by: NET47REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.ServiceModel/v4.0_4.0.0.0__b77a5c561934e089/System.ServiceModel.dll
----------------------------------------
RJCP.SerialPortStream
    Assembly Version: 2.1.1.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///F:/Amiibo%20Stuff/AmiiBomb_0.2_Alpha_by_Ac_K/AmiiBomb.exe
----------------------------------------
IntelHexFormatReader
    Assembly Version: 2.2.2.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///F:/Amiibo%20Stuff/AmiiBomb_0.2_Alpha_by_Ac_K/AmiiBomb.exe
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

@AcK77

**Comment by kokkie20** [comment]
Question, did it save the file or not? 

@Zombuino

**Comment by Zombuino** [comment]
It did not save the file in the dump folder.  I click "Continue" on the error screen and nothing happens.  The Dump Amiibo window remains there but all buttons on this window are grayed out.  I can close this window but there is no file saved for the read Amiibo.  Same result with several different Amiibos.

I have not tried to write to a NTAG215 yet since I will not have some for a few days.  Will try to write one when I receive them.

**Comment by kokkie20** [comment]
Ok that is weird, i just tried one with a ntag 215 amiibo card from me (Bowser) and it just dumped it fine.
I tested it also with a Mario 30th anniv Classic color and dumped fine to.
My guess is there is something wrong with probally the key file, can you send it to me?
Its my nickname and then @gmail.com behind it, will take a look

@Zombuino

**Comment by kokkie20** [comment]
*Problem should be fixed with contact trough email with @Zombuino 👍

**Comment by Zombuino** [comment]
Issue closed.  Had to do with hex key not saving when copied from pastebin web site.  Using key file instead of trying to use pasted hex worked.  

Recommend using actual key file instead of hex from web site.

**Comment by kokkie20** [comment]
i placed pull request for fix of saving hex key from pastebin website so that it does save to a file.
Happy it worked out for you now :)
