### ISSUE TITLE
add other arduino board variants

### ISSUE THREAD

**Issue by h3llb3nt** [AcK77/AmiiBomb-uino#19]
i'm using an adafruit metro mini for my arduino. i was able to grab the source arduino ide files you built and flash it myself but it would be simpler if the xloader or amiibombuino flasher had options for more board variants. my guess is that most will use all the same types but the labels can get people all confused, like i was.

**Comment by kokkie20** [comment]
I hope you do know there are way to many arduino's to compile for all of them right?
It is hard to to keep everyone satisfied, cause everyone can use a different arduino and i am not even sure if all of them can support the rfid reader (Needed pins to connect the rfid reader to. Not sure, i only own 3 kind of arduino's tough)

**Comment by h3llb3nt** [comment]
yes i'm aware there are many many variants. just a suggestion. perhaps at the very least a roadmap for people to follow on what to do if their board variant doesn't work. breadcrumbs.

**Comment by peacepenguin** [comment]
Personally, i feel it is better to REQUIRE the use of the arduino IDE to flash firmware. Helps with getting your feet wet with the arduino eco-system, which is already VERY friendly for non-technical people.

But, if the community wants the feature, perhaps ithe hex files could be auto-compiled when building the solution in visual studio? Currently the solution only builds the windows exe. Anyone have experience in Visual studio for tying in an arduino compilation?

**Comment by kokkie20** [comment]
i had tried a add-on in visual studio so it would be easier to debug the arduino, but all i can say is it didnt work as it should 👎 (Was using "Visual Micro"
As far as i know its not possible within VS without a plugin/tool for it

**Comment by peacepenguin** [comment]
Yea i tried visual micro too without success, glad to hear it wasn't just me. It had nag screens as well... perhaps we can just call the arduino IDE build from the command line, as part of the visual studio solution  build process. 

I'll look into arduino IDE automation, then if that works, how to tie the automation to the overall build process within visual studio.

**Comment by AcK77** [comment]
I thinks it's better to use Arduino IDE for not very popular board. I can't support all of them with the internal flasher and provide a compiled firmware for all of the boards. Sorry.
