### ISSUE TITLE
Enable highest power gain on the MFRC522 module

### ISSUE THREAD

**Issue by standardbus** [AcK77/AmiiBomb-uino#2]
This has to be changed on the MFRC522 library (tested on my NFC module and working for Amiibomb):

Edit MFRC522.cpp Arduino library and find

PCD_AntennaOn();						// Enable the antenna driver pins TX1 and TX2 (they were disabled by the reset)

before the line PCD_AntennaOn(); add this line

PCD_WriteRegister(RFCfgReg, (0x07<<4)); // Set Rx Gain to max

...then save MFRC522.cpp and recompile the AmiiBomb.ino

**Comment by AcK77** [comment]
Big thanks about this feature! I'll try to update the code of AmiiBombuino soon ;) 👍
