### ISSUE TITLE
MIT License violation - attribution required

### ISSUE THREAD

**Issue by christophediericx** [AcK77/AmiiBomb-uino#22]
Hi there,

It seems you have directly incorporated (most of the source files of) an earlier version of my library (https://github.com/christophediericx/ArduinoSketchUploader) in your software.

That is definitely no issue at all (it is open source software meant to be used with a very liberal license) but please note that proper **attribution** (and the inclusion of a license file) is still required as per the terms of the MIT license: https://github.com/christophediericx/ArduinoSketchUploader/blob/master/LICENSE.md.

On a related note, if you want to keep it easier to update the library (as it gains bugfixes etc) you might want to consider linking to the nuget package (https://www.nuget.org/packages/ArduinoUploader/) instead.

Thank you,

Christophe

**Comment by AcK77** [comment]
Commit ce4bea6fee9a16dcea0ce07e1f78a110be456f8e is good for you?

**Comment by christophediericx** [comment]
Sure, that works, thanks!
