### ISSUE TITLE
Keyboard shortcuts

### ISSUE THREAD

**Issue by YozenPL** [AcK77/AmiiBomb-uino#3]
Could you please implement a keyboard shortcuts for dumping and creating TAGs?
Like:
CTRL + D = Dump
CTRL + C = Create NTAG (from selected dump)

**Comment by YozenPL** [comment]
Wrong tab :)

**Comment by YozenPL** [comment]
I thought I have to put it in "Pull request" :D

**Comment by AcK77** [comment]
Good idea ;)! I add this two shortcuts in the next release ;)!

Oh and no problems about the mistake ^^ "issues" are the right place for enhancement!

**Comment by AcK77** [comment]
It's added :)

**Comment by urherenow** [comment]
CTRL+C is a universallyBAD idea. Everyone, including my 70+yo mother uses CTRL+C to copy hilighted text. Using this action to initiate a write? Just, no. Suppose someone has an actual amiibo sitting on their reader when doing this because they just made a personal dump...

**Comment by urherenow** [comment]
Might I suggest CTRL+W instead, meaning "write"?

**Comment by AcK77** [comment]
Hi, don't worry ^^, I used CTRL+D for Dump and CTRL+N for create NTAG, I know for what's CTRL+C is used lool!
