### ISSUE TITLE
build issue on VS studio express 2013

### ISSUE THREAD

**Issue by urherenow** [AcK77/AmiiBomb-uino#4]
not sure why I have that particular version of VS installed... probably for a class. Anyway, I don't know how to get around the error:

The type or namespace name 'RJCP' could not be found (are you missing a using directive or an assembly reference?)

and

The type or namespace name 'SerialPortStream' could not be found <with the same as above added in  () >

**Comment by urherenow** [comment]
Nevermind. Figured it out. Had to update a bunch of stuff both VS and using Nuget...

**Comment by AcK77** [comment]
Yes, it's because you have to install the dependencies through the Nuget Packages ;)!
Hope you compile it with success!
