### ISSUE TITLE
Method Not Found

### ISSUE THREAD

**Issue by vargRSBZ** [AcK77/AmiiBomb-uino#9]
Hello

with the new version, i've got an issue when i launch it or when i click on a menu:

_System.MissingMethodException: Méthode introuvable : '!!0[] System.Array.Empty()'.
   à AmiiBomb.Main_Form.AskBinFolder()
   à AmiiBomb.Main_Form.Main_Form_Shown(Object sender, EventArgs e)
   à System.Windows.Forms.Form.OnShown(EventArgs e)
   à System.Windows.Forms.Form.CallShownEvent()
   à System.Windows.Forms.Control.InvokeMarshaledCallbackDo(ThreadMethodEntry tme)
   à System.Windows.Forms.Control.InvokeMarshaledCallbackHelper(Object obj)
   à System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   à System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   à System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   à System.Windows.Forms.Control.InvokeMarshaledCallback(ThreadMethodEntry tme)
   à System.Windows.Forms.Control.InvokeMarshaledCallbacks()_

I'm on windows 7 , with .NET 4.5.
Do I need something else to make it work?

Cheers

**Comment by AcK77** [comment]
Can you try AmiiBomb with the .NET 4.6.1 installed?

https://www.microsoft.com/fr-fr/download/details.aspx?id=49981

Thanks.

**Comment by vargRSBZ** [comment]
Hello AcK77,

thanks for your reply and your solution is right... I needed .NET 4.6.1.
I could be nice to clearly notice that prerequisite on your page and on GBATEMP.

Good Job !!!!

bye
Marc

**Comment by AcK77** [comment]
Yes I gonna make this precision in the GBATemp thread and in the wiki too ;)! 
It's good to see your issue is resolved now ^^!
